### ISSUE TITLE
ModuleNotFoundError: No module named 'pcapy-ng'

### ISSUE THREAD

**Issue by flinthamm** [stamparm/pcapy-ng#1]
I assume this is something obvious but having done some research now, there doesn't seem to be an obvious solution. I'm trying to use the pcapy module but with python3, which is when I found this fork. Great I thought and promptly installed this (using pip3 install pcapy-ng) after having installed libpcap-dev, python-libpcap, etc. Indeed if I use pip3 freeze, pcapy-ng==1.0.4 appears. pcapy is also installed. 
However the script that works fine with pcapy and python2 just falls at the first hurdle with:
`ModuleNotFoundError: No module named 'pcapy'`

If I change the import statement to import pcapy-ng it fails because of the hyphen, so then if it's changed to:
`pcapy = __import__('pcapy-ng')`
It returns ModuleNotFoundError: No module named 'pcapy-ng'

I would be really grateful if someone could shed some light to what's going on here or an example of the installation commands to install this for use in Python 3? Thank you.

**Comment by stamparm** [comment]
it should actually be `import pcapy` because it is a drop-in replacement for non-maintained `pcapy`

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/160480485-1d3d153e-8631-44bf-915e-f60e5ffc9a11.png)
