### ISSUE TITLE
AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'

### ISSUE THREAD

**Issue by arossert** [stamparm/pcapy-ng#3]
I have posted the same issue in the original `pcapy` repo but it does not seems like it is maintained anymore, any chance of looking at this issue?
https://github.com/helpsystems/pcapy/issues/73
https://github.com/pypa/setuptools/issues/3220

**Comment by stamparm** [comment]
I hope that the latest commit fixes it

**Comment by arossert** [comment]
Thanks for fixing it so quickly

**Comment by isuruf** [comment]
You can get rid of the whole block at https://github.com/stamparm/pcapy-ng/blob/master/setup.py#L47-L64.
It's not needed anymore

**Comment by stamparm** [comment]
@isuruf some more info? what about the backward compatibility (some older python/setuptools installations)?

**Comment by isuruf** [comment]
The code there seems to be for replacing `LDSHARED`'s `gcc` with `g++`, but this is done automatically by distutils/setuptools for almost 20 years now. See https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/distutils/unixccompiler.py#L180-L199

**Comment by isuruf** [comment]
Besides monkeypatching `sysconfig._init_posix` will affect compilation for only `setuptools>=61` and monkeypatching `distutils.sysconfig._init_posix` will affect compilation for `setuptools<61`

**Comment by stamparm** [comment]
@isuruf thx. tested on both python2 and python3
